blank_issues_enabled: false
contact_links:
  - name: Black-mongo Community Support
    url: https://github.com/black-mongo/inn/issues/new?assignees=&labels=&template=feature_request.md&title=
    about: Please ask and answer questions here.
